// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotifyRequest {
    #[prost(enumeration = "Type", tag = "1")]
    pub r#type: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub sequence: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotifyResponse {
    #[prost(enumeration = "Type", tag = "1")]
    pub r#type: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub sequence: u64,
    #[prost(int32, tag = "4")]
    pub error_code: i32,
    #[prost(string, tag = "5")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolVersion {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    #[prost(enumeration = "Arch", tag = "2")]
    pub host: i32,
    #[prost(enumeration = "Arch", tag = "3")]
    pub target: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CrewsResource {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub aliasname: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub devicename: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub addr: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub tool_versions: ::prost::alloc::vec::Vec<ToolVersion>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckCrewsResourceRequest {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub aliasname: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub addr: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckCrewsResourceResponse {
    #[prost(message, repeated, tag = "1")]
    pub resources: ::prost::alloc::vec::Vec<CrewsResource>,
    #[prost(int32, tag = "2")]
    pub error_code: i32,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReportCrewsResourceRequest {
    #[prost(message, repeated, tag = "1")]
    pub resources: ::prost::alloc::vec::Vec<CrewsResource>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReportCrewsResourceResponse {
    #[prost(message, repeated, tag = "1")]
    pub resources: ::prost::alloc::vec::Vec<CrewsResource>,
    #[prost(int32, tag = "2")]
    pub error_code: i32,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Type {
    Unknown = 0,
    Register = 1,
    Unregister = 2,
    Checkresource = 3,
    Keepalive = 4,
    Data = 5,
}
impl Type {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::Register => "REGISTER",
            Self::Unregister => "UNREGISTER",
            Self::Checkresource => "CHECKRESOURCE",
            Self::Keepalive => "KEEPALIVE",
            Self::Data => "DATA",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "REGISTER" => Some(Self::Register),
            "UNREGISTER" => Some(Self::Unregister),
            "CHECKRESOURCE" => Some(Self::Checkresource),
            "KEEPALIVE" => Some(Self::Keepalive),
            "DATA" => Some(Self::Data),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Arch {
    Arm = 0,
    Arm64 = 1,
    X64 = 2,
    X86 = 3,
}
impl Arch {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Arm => "ARM",
            Self::Arm64 => "ARM64",
            Self::X64 => "X64",
            Self::X86 => "X86",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ARM" => Some(Self::Arm),
            "ARM64" => Some(Self::Arm64),
            "X64" => Some(Self::X64),
            "X86" => Some(Self::X86),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod communicate_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct CommunicateClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl CommunicateClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CommunicateClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CommunicateClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            CommunicateClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn notify(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::NotifyRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::NotifyResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/notify.communicate/notify",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut().insert(GrpcMethod::new("notify.communicate", "notify"));
            self.inner.streaming(req, path, codec).await
        }
        pub async fn report_crews_resource(
            &mut self,
            request: impl tonic::IntoRequest<super::ReportCrewsResourceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReportCrewsResourceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/notify.communicate/report_crews_resource",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("notify.communicate", "report_crews_resource"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn cancel_crews_resource(
            &mut self,
            request: impl tonic::IntoRequest<super::ReportCrewsResourceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReportCrewsResourceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/notify.communicate/cancel_crews_resource",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("notify.communicate", "cancel_crews_resource"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn check_crews_resource(
            &mut self,
            request: impl tonic::IntoRequest<super::CheckCrewsResourceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CheckCrewsResourceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/notify.communicate/check_crews_resource",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("notify.communicate", "check_crews_resource"));
            self.inner.unary(req, path, codec).await
        }
    }
}
