
[workspace]
members = ["redirect", "buildassist", "captain", "crew", "tools", "cocrew", "it"]
default-members = ["captain"]
resolver = "2"


[workspace.package]
version = "24.8.0"
edition = "2021"
authors = ["Chang Gu"]
description = "build project increase tool."
documentation = "https://github.com/GuBuChang"


[profile.release]


[profile.dev]
opt-level = 1
debug = true
