
[workspace]
members = ["redirect", "turbobuild", "buildassist", "captain", "crew", "tools", "cocrew"]
default-members = ["turbobuild"]
resolver = "2"


[workspace.package]
version = "24.8.0"
edition = "2021"
authors = ["Chang Gu"]
description = "build project increase tool."
documentation = "https://github.com/GuBuChang"
