[package]
name = "crew"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true


[dependencies]
tools = { path = "../tools" }

tonic = "0.12.3"
prost = "0.13.3"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.129"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "process", "fs"] }
tokio-stream = "0.1.16"
sysinfo = "0.32.0"
winapi = {version = "0.3.9", features = ["winreg", "winerror", "winbase", "fileapi"]}
regex = "1.11.0"
log = "0.4.17"
zip = {version = "2.2.0", features = ["zstd"]}

[build-dependencies]
tonic-build = "0.12.3"


[dev-dependencies]
captain = { path = "../captain" }

[features]
default = []
fake = []