[package]
name = "cocrew"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true


[dependencies]
tools = { path = "../tools" }
crew = { path = "../crew" }
redirectdll = { package = "redirect", path = "../redirect" }

tonic = "0.14.2"
prost = "0.14.1"
tonic-prost = "0.14.2"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "tracing"] }
tokio-stream = "0.1.16"
log = "0.4.22"
zip = {version = "2.2.0", features = ["zstd"]}
windows-sys = {version = "0.60.2", features = ["Win32_System_Pipes", "Win32_System_Threading"]}
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.129"
dashmap = "6.2.1"
bytes = "1.11.1"
#tracing = "0.1.41"
#console-subscriber = "0.4.1"

[build-dependencies]
tonic-prost-build = "0.14.2"

[dev-dependencies]
windows-sys = { version = "0.60.2", features = ["Wdk_Storage_FileSystem", "Win32_System_IO", "Win32_Storage_FileSystem", "Win32_System_Pipes"] }
redirectdll = { package = "redirect", path = "../redirect" }
