// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompileTrRequest {
    #[prost(string, tag = "1")]
    pub solution: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub project: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub file: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub compiler: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub working_dir: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub variety: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "7")]
    pub commands: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bytes = "vec", tag = "8")]
    pub content: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IntermediateResult {
    #[prost(string, tag = "1")]
    pub file: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub content: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompileTrResponse {
    #[prost(enumeration = "CompileProgress", tag = "1")]
    pub progress: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub out: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub err: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "4")]
    pub results: ::prost::alloc::vec::Vec<IntermediateResult>,
    #[prost(uint32, tag = "5")]
    pub status: u32,
    #[prost(string, tag = "6")]
    pub tips: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileTrRequest {
    #[prost(enumeration = "FileType", tag = "1")]
    pub file_type: i32,
    #[prost(string, tag = "2")]
    pub solution: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub project: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub path: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "6")]
    pub content: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileTrResponse {
    #[prost(int32, tag = "1")]
    pub error_code: i32,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CheckResource {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CocrewResource {
    #[prost(string, tag = "1")]
    pub compiler_path: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub winkits_includes_path: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub msvc_includes_path: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub msvc_version: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub error_code: i32,
    #[prost(string, tag = "6")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CompileProgress {
    Other = 0,
    Filetransfer = 1,
    Compilestart = 2,
    Compiling = 3,
    Compiledone = 4,
    Startlink = 5,
    Linkdone = 6,
}
impl CompileProgress {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Other => "OTHER",
            Self::Filetransfer => "FILETRANSFER",
            Self::Compilestart => "COMPILESTART",
            Self::Compiling => "COMPILING",
            Self::Compiledone => "COMPILEDONE",
            Self::Startlink => "STARTLINK",
            Self::Linkdone => "LINKDONE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OTHER" => Some(Self::Other),
            "FILETRANSFER" => Some(Self::Filetransfer),
            "COMPILESTART" => Some(Self::Compilestart),
            "COMPILING" => Some(Self::Compiling),
            "COMPILEDONE" => Some(Self::Compiledone),
            "STARTLINK" => Some(Self::Startlink),
            "LINKDONE" => Some(Self::Linkdone),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FileType {
    Unknown = 0,
    Sourcefiles = 1,
    Precompiledsrcfiles = 2,
    Toolchain = 3,
    Kits = 4,
}
impl FileType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::Sourcefiles => "SOURCEFILES",
            Self::Precompiledsrcfiles => "PRECOMPILEDSRCFILES",
            Self::Toolchain => "TOOLCHAIN",
            Self::Kits => "KITS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "SOURCEFILES" => Some(Self::Sourcefiles),
            "PRECOMPILEDSRCFILES" => Some(Self::Precompiledsrcfiles),
            "TOOLCHAIN" => Some(Self::Toolchain),
            "KITS" => Some(Self::Kits),
            _ => None,
        }
    }
}
/// Generated server implementations.
pub mod communicate_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with CommunicateServer.
    #[async_trait]
    pub trait Communicate: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the transmit_file method.
        type transmit_fileStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::FileTrResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn transmit_file(
            &self,
            request: tonic::Request<tonic::Streaming<super::FileTrRequest>>,
        ) -> std::result::Result<
            tonic::Response<Self::transmit_fileStream>,
            tonic::Status,
        >;
        /// Server streaming response type for the transmit_task method.
        type transmit_taskStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::CompileTrResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn transmit_task(
            &self,
            request: tonic::Request<super::CompileTrRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::transmit_taskStream>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct CommunicateServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> CommunicateServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for CommunicateServer<T>
    where
        T: Communicate,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/pack.communicate/transmit_file" => {
                    #[allow(non_camel_case_types)]
                    struct transmit_fileSvc<T: Communicate>(pub Arc<T>);
                    impl<
                        T: Communicate,
                    > tonic::server::StreamingService<super::FileTrRequest>
                    for transmit_fileSvc<T> {
                        type Response = super::FileTrResponse;
                        type ResponseStream = T::transmit_fileStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::FileTrRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Communicate>::transmit_file(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = transmit_fileSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pack.communicate/transmit_task" => {
                    #[allow(non_camel_case_types)]
                    struct transmit_taskSvc<T: Communicate>(pub Arc<T>);
                    impl<
                        T: Communicate,
                    > tonic::server::ServerStreamingService<super::CompileTrRequest>
                    for transmit_taskSvc<T> {
                        type Response = super::CompileTrResponse;
                        type ResponseStream = T::transmit_taskStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CompileTrRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Communicate>::transmit_task(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = transmit_taskSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for CommunicateServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "pack.communicate";
    impl<T> tonic::server::NamedService for CommunicateServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
