syntax = "proto3";

package pack;

message CompileTrRequest {
    string solution = 1;
    string index = 2;
    string project = 3;
    string file = 4;
    string compiler = 5;
    string working_dir = 6;
    string variety = 7;
    repeated string commands = 8;
    bytes content = 9;
}

enum CompileProgress {
    OTHER = 0;
    FILETRANSFER = 1;
    COMPILESTART = 2;
    COMPILING = 3;
    COMPILEDONE = 4;
    STARTLINK = 5;
    LINKDONE = 6;
}

message IntermediateResult {
    string file = 1;
    bytes content = 2;
}

message CompileTrResponse {
    CompileProgress progress = 1;
    bytes out = 2;
    bytes err = 3;
    repeated IntermediateResult results = 4;
    uint32 status = 5;
    string tips = 6;
}

enum FileType {
    UNKNOWN = 0;
    SOURCEFILES = 1;
    PRECOMPILEDSRCFILES = 2;
    TOOLCHAIN = 3;
    KITS= 4;
}

message FileTrRequest {
    FileType file_type = 1;
    string name = 2;
    string path = 3;
    bytes content = 4;
}

message FileTrResponse {
    int32 error_code = 1;
    string error_message = 2;
}

message CheckResource {

}

message CocrewResource {
    string compiler_path = 1;
    repeated string winkits_includes_path = 2;
    string msvc_includes_path = 3;
    string msvc_version = 4;
    int32 error_code = 5;
    string error_message = 6;
}

service communicate {
    rpc transmit_file(stream FileTrRequest) returns (stream FileTrResponse) {}
    rpc transmit_task(CompileTrRequest) returns (stream CompileTrResponse) {}
}
