syntax = "proto3";

package pack;

message CompileTrRequest {
    string file = 1;
    string compiler = 2;
    string working_dir = 3;
    string variety = 4;
    repeated string commands = 5;
    bytes content = 6;
}

message CompileTrResponse {
    int32 error_code = 1;
    string error_message = 2;
}

enum FileType {
    UNKNOWN = 0;
    TOOLCHAIN = 1;
    KITS= 2;
}

message FileTrRequest {
    FileType file_type = 1;
    string name = 2;
    string path = 3;
    bytes content = 4;
}

message FileTrResponse {
    int32 error_code = 1;
    string error_message = 2;
}

message CheckResource {

}

message CocrewResource {
    string compiler_path = 1;
    repeated string winkits_includes_path = 2;
    string msvc_includes_path = 3;
    string msvc_version = 4;
    int32 error_code = 5;
    string error_message = 6;
}

service communicate {
    rpc transmit_file(FileTrRequest) returns (FileTrResponse) {}
    rpc transmit_compile(CompileTrRequest) returns (stream CompileTrResponse) {}
}
