[package]
name = "redirect"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
crate-type = ["cdylib"]
name = "redirect64"

[dependencies]
tools = { path = "../tools" }

tokio = "1.41.1"
winapi = {version = "0.3.9", features = ["winbase", "handleapi", "minwindef", "consoleapi", "winnt", "memoryapi", "namedpipeapi", "winuser"]}
ntapi = "0.4.1"
chrono = "0.4.38"

[build-dependencies]
