[package]
name = "tools"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true


[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
windows-sys = {version = "0.60", features = ["Wdk_Storage_FileSystem", "Win32_System_IO", "Win32_Storage_FileSystem", "Win32_System_Diagnostics", "Win32_System_Diagnostics_Debug", "Win32_System_Kernel"]}